version: '3.1'

services:

  db:
    image: mysql
    container_name: falemais-mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_DATABASE: falemais
      
  redis:
    image: redis
    container_name: falemais-redis
    command: [ "redis-server", "--protected-mode", "no" ]
    ports:
      - 6379:6379

  adminer:
    image: adminer
    container_name: falemais-adminer
    restart: always
    ports:
      - 8080:8080

  # PHP (with nginx)
  app:
    image: ambientum/php:7.2-nginx
    container_name: falemais-app
    volumes:
      - .:/var/www/app
    ports:
      - "80:8080"
    links:
      - db
      - adminer
